
project_id = "egfmdynahaaxylxiclxi"

[functions.send-verification]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.log-admin-action]
verify_jwt = true

[functions.get-admin-activity]
verify_jwt = true
