// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egfmdynahaaxylxiclxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZm1keW5haGFheHlseGljbHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNTExMzgsImV4cCI6MjA2MTYyNzEzOH0.T5yyBmJ7WLAzSlUEiLNx9idqPMo2XEhqNpkFqNZbFq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);