name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Change if your build outputs to a subfolder
      - uses: actions/deploy-pages@v4

